/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.schoolsoftware.view;

import ec.edu.espe.schoolsoftware.model.Session;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();

        String role = Session.currentUser.getRole();

        switch (role) {

            case "ADMIN":
                break;

            case "TEACHER":
                menuManage.setVisible(false);
                break;

            case "STUDENT":
                menuManage.setVisible(false);
                menuActivities.setVisible(false);
                menuAlerts.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFiles = new javax.swing.JMenu();
        itmLogOut = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        itmAddStudent = new javax.swing.JMenuItem();
        itmUpdateStudent = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        itmAddTeacher = new javax.swing.JMenuItem();
        itmUpdateTeacher = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        itmAddCourse = new javax.swing.JMenuItem();
        itmUpdateCourse = new javax.swing.JMenuItem();
        menuCourses = new javax.swing.JMenu();
        menuActivities = new javax.swing.JMenu();
        itmCreateActivity = new javax.swing.JMenuItem();
        itmRecordActivity = new javax.swing.JMenuItem();
        menuAlerts = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFiles.setText("Archivo");

        itmLogOut.setText("Cerrar sesión");
        itmLogOut.addActionListener(this::itmLogOutActionPerformed);
        menuFiles.add(itmLogOut);

        itmExit.setText("Salir");
        itmExit.addActionListener(this::itmExitActionPerformed);
        menuFiles.add(itmExit);

        jMenuBar1.add(menuFiles);

        menuManage.setText("Manejar");

        jMenu6.setText("Estudiantes");

        itmAddStudent.setText("Añadir");
        itmAddStudent.addActionListener(this::itmAddStudentActionPerformed);
        jMenu6.add(itmAddStudent);

        itmUpdateStudent.setText("Actualizar");
        itmUpdateStudent.addActionListener(this::itmUpdateStudentActionPerformed);
        jMenu6.add(itmUpdateStudent);

        menuManage.add(jMenu6);

        jMenu7.setText("Profesores");

        itmAddTeacher.setText("Añadir");
        jMenu7.add(itmAddTeacher);

        itmUpdateTeacher.setText("Actualizar");
        jMenu7.add(itmUpdateTeacher);

        menuManage.add(jMenu7);

        jMenu8.setText("Cursos");

        itmAddCourse.setText("Agregar");
        jMenu8.add(itmAddCourse);

        itmUpdateCourse.setText("Actualizar");
        jMenu8.add(itmUpdateCourse);

        menuManage.add(jMenu8);

        jMenuBar1.add(menuManage);

        menuCourses.setText("Mis Cursos");
        jMenuBar1.add(menuCourses);

        menuActivities.setText("Actividades");

        itmCreateActivity.setText("Crear");
        menuActivities.add(itmCreateActivity);

        itmRecordActivity.setText("Calificar");
        menuActivities.add(itmRecordActivity);

        jMenuBar1.add(menuActivities);

        menuAlerts.setText("Alertas");

        jMenuItem8.setText("Bajo rendimiento");
        menuAlerts.add(jMenuItem8);

        jMenuBar1.add(menuAlerts);

        jMenu5.setText("Ayuda");

        jMenuItem7.setText("Acerca de");
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddStudentActionPerformed
        // TODO add your handling code here:
        FrmAddStudent frmStudent = new FrmAddStudent();
        frmStudent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddStudentActionPerformed

    private void itmUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateStudentActionPerformed
        FrmManageStudent frmStudent = new FrmManageStudent();
        frmStudent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateStudentActionPerformed

    private void itmLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogOutActionPerformed
        Session.currentUser = null;

        FrmLogin login = new FrmLogin();

        login.setVisible(true);

        dispose();
    }//GEN-LAST:event_itmLogOutActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAddCourse;
    private javax.swing.JMenuItem itmAddStudent;
    private javax.swing.JMenuItem itmAddTeacher;
    private javax.swing.JMenuItem itmCreateActivity;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmLogOut;
    private javax.swing.JMenuItem itmRecordActivity;
    private javax.swing.JMenuItem itmUpdateCourse;
    private javax.swing.JMenuItem itmUpdateStudent;
    private javax.swing.JMenuItem itmUpdateTeacher;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu menuActivities;
    private javax.swing.JMenu menuAlerts;
    private javax.swing.JMenu menuCourses;
    private javax.swing.JMenu menuFiles;
    private javax.swing.JMenu menuManage;
    // End of variables declaration//GEN-END:variables
}
