/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.schoolsoftware.view;

import ec.edu.espe.schoolsoftware.controller.ActivityController;
import ec.edu.espe.schoolsoftware.controller.GradeController;
import ec.edu.espe.schoolsoftware.controller.ICreate;
import ec.edu.espe.schoolsoftware.controller.MaterialController;
import ec.edu.espe.schoolsoftware.model.Activity;
import ec.edu.espe.schoolsoftware.model.Course;
import ec.edu.espe.schoolsoftware.model.Grade;
import ec.edu.espe.schoolsoftware.model.Material;
import ec.edu.espe.schoolsoftware.repository.MaterialRepository;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmCourseDetails extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCourseDetails.class.getName());

    /**
     * Creates new form FrmCourseDetails
     */
    public FrmCourseDetails(Course course) {
        
        initComponents();
        loadCourseInformation(course);

        loadActivities(course.getId());
        loadMaterials(course.getId());
    }

    private void loadCourseInformation(Course course) {
        lblCourseName.setText(course.getName());
        lblTeacher.setText(course.getTeacherId());
    }

    private void loadActivities(String courseId) {

        ActivityController activityController = new ActivityController();

        ArrayList<Activity> activities = activityController.getActivityRepository().findByCourseId(courseId);

        fillActivitiesTable(activities);

    }

    private void fillActivitiesTable(ArrayList<Activity> activities) {
        DefaultTableModel model = (DefaultTableModel) tblActivities.getModel();
        model.setRowCount(0);

        for (Activity activity : activities) {

            Object[] row = {
                activity.getId(),
                activity.getCourseId(),
                activity.getTitle()
            };

            model.addRow(row);
        }
    }

    private void loadMaterials(String courseId) {

        MaterialController materialController = new MaterialController(new MaterialRepository());
        ArrayList<Material> materials = materialController.findByCourseId(courseId);
        fillMaterialsTable(materials);

    }

    private void fillMaterialsTable(ArrayList<Material> materials) {
        DefaultTableModel model = (DefaultTableModel) tblMaterials.getModel();
        model.setRowCount(0);

        for (Material material : materials) {

            Object[] row = {
                material.getId(),
                material.getTitle(),
                material.getFileType()
            };

            model.addRow(row);
        }
    }

    private void loadGrades(String courseId) {

        GradeController gradeController = new GradeController();
        ArrayList<Grade> grades = gradeController.getGradeRepository().findByCourseId(courseId);

        fillGradesTable(grades);

    }

    private void fillGradesTable(ArrayList<Grade> grades) {
        DefaultTableModel model = (DefaultTableModel) tblGrades.getModel();
        model.setRowCount(0);

        for (Grade grade : grades) {

            Object[] row = {
                grade.getId(),
                grade.getStudentId(),
                grade.getScore(),
                grade.getFeedback()
            };

            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtons = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        btnDoActivity = new javax.swing.JButton();
        btnBackToMyCourses = new javax.swing.JButton();
        pnlHeader = new javax.swing.JPanel();
        lblCourseName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTeacher = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlActivities = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblActivities = new javax.swing.JTable();
        pnlMaterials = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMaterials = new javax.swing.JTable();
        pnlQuizzes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblQuizzes = new javax.swing.JTable();
        pnlGrades = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblGrades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBackToMenu.setText("Volver al Menu");
        btnBackToMenu.addActionListener(this::btnBackToMenuActionPerformed);

        btnDoActivity.setText("Realizar Actividad");

        btnBackToMyCourses.setText("Volver a mis cursos");
        btnBackToMyCourses.addActionListener(this::btnBackToMyCoursesActionPerformed);

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnDoActivity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(btnBackToMyCourses)
                .addGap(35, 35, 35))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToMenu)
                    .addComponent(btnDoActivity)
                    .addComponent(btnBackToMyCourses))
                .addGap(18, 18, 18))
        );

        lblCourseName.setText("Course Name");

        jLabel1.setText("Profesor:");

        lblTeacher.setText("Nombre Profesor");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lblCourseName))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(lblTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCourseName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTeacher))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tblActivities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblActivities);

        javax.swing.GroupLayout pnlActivitiesLayout = new javax.swing.GroupLayout(pnlActivities);
        pnlActivities.setLayout(pnlActivitiesLayout);
        pnlActivitiesLayout.setHorizontalGroup(
            pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivitiesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlActivitiesLayout.setVerticalGroup(
            pnlActivitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivitiesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actividades", pnlActivities);

        tblMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMaterials);

        javax.swing.GroupLayout pnlMaterialsLayout = new javax.swing.GroupLayout(pnlMaterials);
        pnlMaterials.setLayout(pnlMaterialsLayout);
        pnlMaterialsLayout.setHorizontalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlMaterialsLayout.setVerticalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaterialsLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Materiales", pnlMaterials);

        tblQuizzes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblQuizzes);

        javax.swing.GroupLayout pnlQuizzesLayout = new javax.swing.GroupLayout(pnlQuizzes);
        pnlQuizzes.setLayout(pnlQuizzesLayout);
        pnlQuizzesLayout.setHorizontalGroup(
            pnlQuizzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizzesLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlQuizzesLayout.setVerticalGroup(
            pnlQuizzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizzesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quizzes", pnlQuizzes);

        tblGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblGrades);

        javax.swing.GroupLayout pnlGradesLayout = new javax.swing.GroupLayout(pnlGrades);
        pnlGrades.setLayout(pnlGradesLayout);
        pnlGradesLayout.setHorizontalGroup(
            pnlGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGradesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnlGradesLayout.setVerticalGroup(
            pnlGradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGradesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calificaciones", pnlGrades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnBackToMyCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMyCoursesActionPerformed
        
        FrmMyCourses frmMyCourses = new FrmMyCourses();
        frmMyCourses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMyCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnBackToMyCourses;
    private javax.swing.JButton btnDoActivity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JPanel pnlActivities;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlGrades;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMaterials;
    private javax.swing.JPanel pnlQuizzes;
    private javax.swing.JTable tblActivities;
    private javax.swing.JTable tblGrades;
    private javax.swing.JTable tblMaterials;
    private javax.swing.JTable tblQuizzes;
    // End of variables declaration//GEN-END:variables
}
