/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.schoolsoftware.view;

import ec.edu.espe.schoolsoftware.model.Session;

/**
 *
 * @author Daniel Codena, CodeBreakers, @ESPE
 */
public class FrmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();

        String role = Session.currentUser.getRole();

        switch (role) {

            case "ADMIN":
                break;

            case "TEACHER":
                menuManage.setVisible(false);
                break;

            case "STUDENT":
                menuManage.setVisible(false);
                menuActivities.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFiles = new javax.swing.JMenu();
        itmLogOut = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        itmAddStudent = new javax.swing.JMenuItem();
        itmUpdateStudent = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        itmAddTeacher = new javax.swing.JMenuItem();
        itmUpdateTeacher = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        itmAddCourse = new javax.swing.JMenuItem();
        itmUpdateCourse = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itmAddEnrollment = new javax.swing.JMenuItem();
        itmUpdateEnrollment = new javax.swing.JMenuItem();
        menuCourses = new javax.swing.JMenu();
        menuActivities = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        itmAddActivity = new javax.swing.JMenuItem();
        itmUpdateActivities = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmAddQuiz = new javax.swing.JMenuItem();
        itmUpdateQuizzes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmAddGrade = new javax.swing.JMenuItem();
        itmUpdateGrades = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itmAddMaterial = new javax.swing.JMenuItem();
        itmUpdateMaterials = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFiles.setText("Archivo");

        itmLogOut.setText("Cerrar sesión");
        itmLogOut.addActionListener(this::itmLogOutActionPerformed);
        menuFiles.add(itmLogOut);

        itmExit.setText("Salir");
        itmExit.addActionListener(this::itmExitActionPerformed);
        menuFiles.add(itmExit);

        jMenuBar1.add(menuFiles);

        menuManage.setText("Manejar");

        jMenu6.setText("Estudiantes");

        itmAddStudent.setText("Añadir");
        itmAddStudent.addActionListener(this::itmAddStudentActionPerformed);
        jMenu6.add(itmAddStudent);

        itmUpdateStudent.setText("Administrar");
        itmUpdateStudent.addActionListener(this::itmUpdateStudentActionPerformed);
        jMenu6.add(itmUpdateStudent);

        menuManage.add(jMenu6);

        jMenu7.setText("Profesores");

        itmAddTeacher.setText("Añadir");
        itmAddTeacher.addActionListener(this::itmAddTeacherActionPerformed);
        jMenu7.add(itmAddTeacher);

        itmUpdateTeacher.setText("Administrar");
        itmUpdateTeacher.addActionListener(this::itmUpdateTeacherActionPerformed);
        jMenu7.add(itmUpdateTeacher);

        menuManage.add(jMenu7);

        jMenu8.setText("Cursos");

        itmAddCourse.setText("Agregar");
        itmAddCourse.addActionListener(this::itmAddCourseActionPerformed);
        jMenu8.add(itmAddCourse);

        itmUpdateCourse.setText("Administrar");
        itmUpdateCourse.addActionListener(this::itmUpdateCourseActionPerformed);
        jMenu8.add(itmUpdateCourse);

        menuManage.add(jMenu8);

        jMenu1.setText("Inscripciones");

        itmAddEnrollment.setText("Añadir");
        itmAddEnrollment.addActionListener(this::itmAddEnrollmentActionPerformed);
        jMenu1.add(itmAddEnrollment);

        itmUpdateEnrollment.setText("Administrar");
        itmUpdateEnrollment.addActionListener(this::itmUpdateEnrollmentActionPerformed);
        jMenu1.add(itmUpdateEnrollment);

        menuManage.add(jMenu1);

        jMenuBar1.add(menuManage);

        menuCourses.setText("Mis Cursos");
        jMenuBar1.add(menuCourses);

        menuActivities.setText("Actividades");

        jMenu9.setText("Actividades");

        itmAddActivity.setText("Añadir");
        itmAddActivity.addActionListener(this::itmAddActivityActionPerformed);
        jMenu9.add(itmAddActivity);

        itmUpdateActivities.setText("Administrar");
        itmUpdateActivities.addActionListener(this::itmUpdateActivitiesActionPerformed);
        jMenu9.add(itmUpdateActivities);

        menuActivities.add(jMenu9);

        jMenu2.setText("Quizzes");

        itmAddQuiz.setText("Añadir");
        itmAddQuiz.addActionListener(this::itmAddQuizActionPerformed);
        jMenu2.add(itmAddQuiz);

        itmUpdateQuizzes.setText("Administrar");
        itmUpdateQuizzes.addActionListener(this::itmUpdateQuizzesActionPerformed);
        jMenu2.add(itmUpdateQuizzes);

        menuActivities.add(jMenu2);

        jMenu3.setText("Calificaciones");

        itmAddGrade.setText("Añadir");
        itmAddGrade.addActionListener(this::itmAddGradeActionPerformed);
        jMenu3.add(itmAddGrade);

        itmUpdateGrades.setText("Administrar");
        itmUpdateGrades.addActionListener(this::itmUpdateGradesActionPerformed);
        jMenu3.add(itmUpdateGrades);

        menuActivities.add(jMenu3);

        jMenu4.setText("Materiales");

        itmAddMaterial.setText("Añadir");
        itmAddMaterial.addActionListener(this::itmAddMaterialActionPerformed);
        jMenu4.add(itmAddMaterial);

        itmUpdateMaterials.setText("Administrar");
        itmUpdateMaterials.addActionListener(this::itmUpdateMaterialsActionPerformed);
        jMenu4.add(itmUpdateMaterials);

        menuActivities.add(jMenu4);

        jMenuBar1.add(menuActivities);

        jMenu5.setText("Ayuda");

        jMenuItem7.setText("Acerca de");
        jMenu5.add(jMenuItem7);

        jMenuItem2.setText("Guía");
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddStudentActionPerformed
        // TODO add your handling code here:
        FrmAddStudent frmStudent = new FrmAddStudent();
        frmStudent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddStudentActionPerformed

    private void itmUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateStudentActionPerformed
        FrmManageStudent frmStudent = new FrmManageStudent();
        frmStudent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateStudentActionPerformed

    private void itmLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogOutActionPerformed
        Session.currentUser = null;

        FrmLogin login = new FrmLogin();

        login.setVisible(true);

        dispose();
    }//GEN-LAST:event_itmLogOutActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    private void itmAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddTeacherActionPerformed
        FrmAddTeacher frmAddTeacher = new FrmAddTeacher();
        frmAddTeacher.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddTeacherActionPerformed

    private void itmUpdateTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateTeacherActionPerformed
        FrmManageTeacher frmManageTeacher = new FrmManageTeacher();
        frmManageTeacher.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateTeacherActionPerformed

    private void itmAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddCourseActionPerformed
        FrmAddCourse frmAddCourse = new FrmAddCourse();
        frmAddCourse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddCourseActionPerformed

    private void itmUpdateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateCourseActionPerformed
        FrmManageCourse frmManageCourse = new FrmManageCourse();
        frmManageCourse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateCourseActionPerformed

    private void itmAddActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddActivityActionPerformed
        FrmAddActivity frmAdd = new FrmAddActivity();
        frmAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddActivityActionPerformed

    private void itmAddQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddQuizActionPerformed
        FrmAddQuiz frmAdd = new FrmAddQuiz();
        frmAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddQuizActionPerformed

    private void itmAddGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddGradeActionPerformed

    }//GEN-LAST:event_itmAddGradeActionPerformed

    private void itmAddMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddMaterialActionPerformed
        FrmAddMaterial frmAdd = new FrmAddMaterial();
        frmAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmAddMaterialActionPerformed

    private void itmUpdateActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateActivitiesActionPerformed
        FrmManageActivity frmManage = new FrmManageActivity();
        frmManage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateActivitiesActionPerformed

    private void itmUpdateQuizzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateQuizzesActionPerformed
        FrmManageQuiz frmManage = new FrmManageQuiz();
        frmManage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateQuizzesActionPerformed

    private void itmUpdateGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateGradesActionPerformed

    }//GEN-LAST:event_itmUpdateGradesActionPerformed

    private void itmUpdateMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateMaterialsActionPerformed
        FrmManageMaterial frmManage = new FrmManageMaterial();
        frmManage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itmUpdateMaterialsActionPerformed

    private void itmAddEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddEnrollmentActionPerformed

    }//GEN-LAST:event_itmAddEnrollmentActionPerformed

    private void itmUpdateEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmUpdateEnrollmentActionPerformed


        this.setVisible(false);    }//GEN-LAST:event_itmUpdateEnrollmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAddActivity;
    private javax.swing.JMenuItem itmAddCourse;
    private javax.swing.JMenuItem itmAddEnrollment;
    private javax.swing.JMenuItem itmAddGrade;
    private javax.swing.JMenuItem itmAddMaterial;
    private javax.swing.JMenuItem itmAddQuiz;
    private javax.swing.JMenuItem itmAddStudent;
    private javax.swing.JMenuItem itmAddTeacher;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmLogOut;
    private javax.swing.JMenuItem itmUpdateActivities;
    private javax.swing.JMenuItem itmUpdateCourse;
    private javax.swing.JMenuItem itmUpdateEnrollment;
    private javax.swing.JMenuItem itmUpdateGrades;
    private javax.swing.JMenuItem itmUpdateMaterials;
    private javax.swing.JMenuItem itmUpdateQuizzes;
    private javax.swing.JMenuItem itmUpdateStudent;
    private javax.swing.JMenuItem itmUpdateTeacher;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuActivities;
    private javax.swing.JMenu menuCourses;
    private javax.swing.JMenu menuFiles;
    private javax.swing.JMenu menuManage;
    // End of variables declaration//GEN-END:variables
}
